In [18]:
lab02 <- read.csv('Lab02_Ex1.csv', header=TRUE)
attach(lab02)
lab02 <- lab02[order(Weight),];lab02
lab02[lab02$Weight > 3000,]
lab02[lab02$Weight > 3000 & lab02$Horsepower > 200,]
lab02[lab02$Weight > 3000, 'MPG']

#subset(lab02, Weight>3000)
#subset(lab02, Weight>3000 & Horsepower>200)

The following objects are masked from lab02 (pos = 3):

    Car, Displacement, Horsepower, Model, MPG, Origin, Weight

The following objects are masked from lab02 (pos = 4):

    Car, Displacement, Horsepower, Model, MPG, Origin, Weight

The following objects are masked from lab02 (pos = 5):

    Car, Displacement, Horsepower, Model, MPG, Origin, Weight

The following objects are masked from lab02 (pos = 6):

    Car, Displacement, Horsepower, Model, MPG, Origin, Weight

The following objects are masked from lab02 (pos = 7):

    Car, Displacement, Horsepower, Model, MPG, Origin, Weight

The following objects are masked from lab02 (pos = 8):

    Car, Displacement, Horsepower, Model, MPG, Origin, Weight

The following objects are masked from lab02 (pos = 9):

    Car, Displacement, Horsepower, Model, MPG, Origin, Weight

The following objects are masked from lab02 (pos = 10):

    Car, Displacement, Horsepower, Model, MPG, Origin, Weight

The following objects are masked from lab02 (pos = 11):

    Car, Displacement, Horsepower, Model, MPG, Origin, Weight

The following objects are masked from lab02 (pos = 12):

    Car, Displacement, Horsepower, Model, MPG, Origin, Weight

The following objects are masked from lab02 (pos = 13):

    Car, Displacement, Horsepower, Model, MPG, Origin, Weight

The following objects are masked from lab02 (pos = 14):

    Car, Displacement, Horsepower, Model, MPG, Origin, Weight

The following objects are masked from lab02 (pos = 15):

    Car, Displacement, Horsepower, Model, MPG, Origin, Weight

The following objects are masked from lab02 (pos = 16):

    Car, Displacement, Horsepower, Model, MPG, Origin, Weight

   Car                MPG  Displacement Horsepower Weight Model Origin
7  Honda Civic CVCC   36.1  91           60        1800   78    Japan
3  Volkswagen Rabbit  29.0  90           70        1937   75    Europe
1  Peugeot 304        30.0  79           70        2074   71    Europe
12 Chevrolet Chevette 30.0  98           68        2155   78    US
5  Toyota Corolla     25.0 113           95        2228   71    Japan
6  Subaru FT          26.0 108           93        2391   74    Japan
2  Audi 100LS         20.0 114           91        2582   73    Europe
8  Datsun 810         22.0 146           97        2815   77    Japan
4  Volvo 245          20.0 130          102        3150   76    Europe
10 Chevy C20          10.0 307          200        4376   70    US
9  Ford F250          10.0 360          215        4615   70    US
11 Pontiac Catalina   16.0 400          170        4668   75    US

   Car              MPG Displacement Horsepower Weight Model Origin
4  Volvo 245        20  130          102        3150   76    Europe
10 Chevy C20        10  307          200        4376   70    US
9  Ford F250        10  360          215        4615   70    US
11 Pontiac Catalina 16  400          170        4668   75    US

  Car       MPG Displacement Horsepower Weight Model Origin
9 Ford F250 10  360          215        4615   70    US

[1] 20 10 10 16

In [21]:
columns = c('id', 'gender', 'height', 'weight', 'siblings')
lab2 <- read.fwf('Lab02fixed.txt', width=c(3,1,3,2,1), col.names=columns)
lab2m <- lab2[lab2$gender=='M',];lab2m  # Subsets dataframe to male subjects 
nrow(lab2m)  # Number of male subjects

lab2fixed <- read.table('Lab02test.txt', header=T); lab2fixed
##lab2merge <- cbind(lab2, lab2fixed); lab2merge[,6] <- NULL; lab2merge  # Need to remove duplicate id column with cbind
lab2merge <- merge(lab2, lab2fixed, by="id"); lab2merge  # Merges dataframes by common column
df_ht182 <- lab2merge[lab2merge$height>182,]; df_ht182  # Test scores of subjects with height > 182

lab2remo <- subset(lab2, id!=211); lab2remo  # Subsets dataframe to id's that are not 211
lab2remo <- lab2[-11,]  # Same as above but by index of row

lab2[lab2$id==211,'weight'] <- 60  # Replace weight of subject 211 with 60
lab2$id[lab2$id==211,] <- 'XX'; lab2  # Replace subject id of 211 with XX

lab2f <- lab2merge[lab2merge$gender=='F',];lab2f  # Subsets dataframe to female subjects
attach(lab2f)
lab2f <- lab2f[order(-height),]; lab2f  # Sorts height by descending order
lab2f[2, c('height', 'weight', 'test')]  # Height, weight and test score of 2nd tallest female

    id  gender height weight siblings
1   201 M      173    65     1
5   205 M      169    58     1
6   206 M      171    63     2
10  210 M      168    88     1
11  211 M      171    99     3
15  215 M      164    54     1
17  217 M      175    60     1
18  218 M      165    61     2
20  220 M      179    81     2
23  223 M      175    58     1
24  224 M      165    68     2
25  225 M      168    54     1
30  230 M      172    64     2
31  231 M      177    57     2
41  241 M      164    59     2
42  242 M      170    57     0
49  249 M      176    75     2
52  252 M      170    80     1
53  253 M      174    73     1
58  258 M      168    58     1
65  265 M      172    70     2
66  266 M      180    70     1
67  267 M      183    85     0
70  270 M      180    65     3
71  271 M      188    60     2
72  272 M      172    70     1
74  274 M      173    67     1
77  277 M      182    67     1
83  283 M      180    79     1
85  285 M      184    67     3
87  287 M      174    52     1
90  290 M      175    73     2
91  291 M      178    62     1
93  293 M      182    58     2
95  295 M      168    73     1
97  297 M      170    57     1
98  298 M      175    70     1
100 300 M      163    56     3
101 301 M      170    61     3
102 302 M      175    78     0
103 303 M      182    74     2
105 305 M      182    69     2
107 307 M      182    78     1
110 310 M      178    74     2
114 314 M      166    63     1
117 317 M      175    64     2
118 318 M      175    67     1
120 320 M      171    68     3

[1] 48

    id  test
1   201 67
2   202 64
3   203 67
4   204 81
5   205 86
6   206 69
7   207 81
8   208 82
9   209 67
10  210 81
11  211 64
12  212 70
13  213 59
14  214 69
15  215 69
16  216 60
17  217 57
18  218 78
19  219 71
20  220 78
21  221 90
22  222 77
23  223 72
24  224 70
25  225 71
26  226 63
27  227 81
28  228 86
29  229 71
30  230 53
... ... ...
91  291 79
92  292 66
93  293 63
94  294 63
95  295 68
96  296 74
97  297 78
98  298 60
99  299 47
100 300 68
101 301 76
102 302 92
103 303 93
104 304 87
105 305 73
106 306 59
107 307 60
108 308 51
109 309 68
110 310 83
111 311 82
112 312 94
113 313 82
114 314 68
115 315 59
116 316 62
117 317 66
118 318 65
119 319 70
120 320 65

    id  gender height weight siblings test
1   201 M      173    65     1        67
2   202 F      158    47     1        64
3   203 F      158    43     2        67
4   204 F      162    45     2        81
5   205 M      169    58     1        86
6   206 M      171    63     2        69
7   207 F      167    47     2        81
8   208 F      157    44     2        82
9   209 F      163    48     2        67
10  210 M      168    88     1        81
11  211 M      171    99     3        64
12  212 F      163    59     4        70
13  213 F      162    48     0        59
14  214 F      167    52     0        69
15  215 M      164    54     1        69
16  216 F      161    49     1        60
17  217 M      175    60     1        57
18  218 M      165    61     2        78
19  219 F      165    48     2        71
20  220 M      179    81     2        78
21  221 F      164    53     1        90
22  222 F      161    49     1        77
23  223 M      175    58     1        72
24  224 M      165    68     2        70
25  225 M      168    54     1        71
26  226 F      162    52     1        63
27  227 F      157    48     2        81
28  228 F      167    58     1        86
29  229 F      159    57     2        71
30  230 M      172    64     2        53
... ... ...    ...    ...    ...      ...
91  291 M      178    62     1        79
92  292 F      165    47     1        66
93  293 M      182    58     2        63
94  294 F      161    45     1        63
95  295 M      168    73     1        68
96  296 F      166    67     2        74
97  297 M      170    57     1        78
98  298 M      175    70     1        60
99  299 F      178    55     1        47
100 300 M      163    56     3        68
101 301 M      170    61     3        76
102 302 M      175    78     0        92
103 303 M      182    74     2        93
104 304 F      153    49     2        87
105 305 M      182    69     2        73
106 306 F      156    46     2        59
107 307 M      182    78     1        60
108 308 F      158    57     1        51
109 309 F      170    54     2        68
110 310 M      178    74     2        83
111 311 F      160    56     1        82
112 312 F      154    48     2        94
113 313 F      167    51     1        82
114 314 M      166    63     1        68
115 315 F      153    46     0        59
116 316 F      159    53     0        62
117 317 M      175    64     2        66
118 318 M      175    67     1        65
119 319 F      161    50     2        70
120 320 M      171    68     3        65

   id  gender height weight siblings test
67 267 M      183    85     0        55
71 271 M      188    60     2        76
85 285 M      184    67     3        54

    id  gender height weight siblings
1   201 M      173    65     1
2   202 F      158    47     1
3   203 F      158    43     2
4   204 F      162    45     2
5   205 M      169    58     1
6   206 M      171    63     2
7   207 F      167    47     2
8   208 F      157    44     2
9   209 F      163    48     2
10  210 M      168    88     1
12  212 F      163    59     4
13  213 F      162    48     0
14  214 F      167    52     0
15  215 M      164    54     1
16  216 F      161    49     1
17  217 M      175    60     1
18  218 M      165    61     2
19  219 F      165    48     2
20  220 M      179    81     2
21  221 F      164    53     1
22  222 F      161    49     1
23  223 M      175    58     1
24  224 M      165    68     2
25  225 M      168    54     1
26  226 F      162    52     1
27  227 F      157    48     2
28  228 F      167    58     1
29  229 F      159    57     2
30  230 M      172    64     2
31  231 M      177    57     2
... ... ...    ...    ...    ...
91  291 M      178    62     1
92  292 F      165    47     1
93  293 M      182    58     2
94  294 F      161    45     1
95  295 M      168    73     1
96  296 F      166    67     2
97  297 M      170    57     1
98  298 M      175    70     1
99  299 F      178    55     1
100 300 M      163    56     3
101 301 M      170    61     3
102 302 M      175    78     0
103 303 M      182    74     2
104 304 F      153    49     2
105 305 M      182    69     2
106 306 F      156    46     2
107 307 M      182    78     1
108 308 F      158    57     1
109 309 F      170    54     2
110 310 M      178    74     2
111 311 F      160    56     1
112 312 F      154    48     2
113 313 F      167    51     1
114 314 M      166    63     1
115 315 F      153    46     0
116 316 F      159    53     0
117 317 M      175    64     2
118 318 M      175    67     1
119 319 F      161    50     2
120 320 M      171    68     3

ERROR: Error in lab2$id[id == 211, ] <- "XX": object 'id' not found

    id  gender height weight siblings
1   201 M      173    65     1
2   202 F      158    47     1
3   203 F      158    43     2
4   204 F      162    45     2
5   205 M      169    58     1
6   206 M      171    63     2
7   207 F      167    47     2
8   208 F      157    44     2
9   209 F      163    48     2
10  210 M      168    88     1
11  211 M      171    60     3
12  212 F      163    59     4
13  213 F      162    48     0
14  214 F      167    52     0
15  215 M      164    54     1
16  216 F      161    49     1
17  217 M      175    60     1
18  218 M      165    61     2
19  219 F      165    48     2
20  220 M      179    81     2
21  221 F      164    53     1
22  222 F      161    49     1
23  223 M      175    58     1
24  224 M      165    68     2
25  225 M      168    54     1
26  226 F      162    52     1
27  227 F      157    48     2
28  228 F      167    58     1
29  229 F      159    57     2
30  230 M      172    64     2
... ... ...    ...    ...    ...
91  291 M      178    62     1
92  292 F      165    47     1
93  293 M      182    58     2
94  294 F      161    45     1
95  295 M      168    73     1
96  296 F      166    67     2
97  297 M      170    57     1
98  298 M      175    70     1
99  299 F      178    55     1
100 300 M      163    56     3
101 301 M      170    61     3
102 302 M      175    78     0
103 303 M      182    74     2
104 304 F      153    49     2
105 305 M      182    69     2
106 306 F      156    46     2
107 307 M      182    78     1
108 308 F      158    57     1
109 309 F      170    54     2
110 310 M      178    74     2
111 311 F      160    56     1
112 312 F      154    48     2
113 313 F      167    51     1
114 314 M      166    63     1
115 315 F      153    46     0
116 316 F      159    53     0
117 317 M      175    64     2
118 318 M      175    67     1
119 319 F      161    50     2
120 320 M      171    68     3

In [1]:
week1 <- c(16, 9, 13, 5, 2, 17, 14)
week2 <- c(17, 7, 5, 16, 8, 13, 14)
matrix((c(week1, week2)), nrow=2, byrow=TRUE)
week1[week1 >= 14]
week1[week2 >= 14]  # Gives corresponding data where week2 >= 14

     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 16   9    13    5   2    17   14
[2,] 17   7     5   16   8    13   14

[1] 16 17 14

[1] 16  5 14

In [16]:
func1 <- function(x){
    if (x < 100) {
        if (x < 10) {
            result <- 'single digit'
        }
        else {
            result <- 'double digits'
        }
    }
    else if (x <= 999) {
        result <- 'triple digits'
    }
    else {
        result <- 'more than 3 digits'
    }
    print(paste(x, 'is', result))
}

func1(5000)

[1] "5000 is more than 3 digits"

In [7]:
statquote <- 'There are three types of lies -- lies, damn lies, and statistics'
chars <- strsplit(statquote, split = '')[[1]]; chars
ectr <- 0 
for (char in chars) {
    if (char == "e") {
        ectr <- ectr +1
    }
}
print(ectr)

 [1] "T" "h" "e" "r" "e" " " "a" "r" "e" " " "t" "h" "r" "e" "e" " " "t" "y" "p"
[20] "e" "s" " " "o" "f" " " "l" "i" "e" "s" " " "-" "-" " " "l" "i" "e" "s" ","
[39] " " "d" "a" "m" "n" " " "l" "i" "e" "s" "," " " "a" "n" "d" " " "s" "t" "a"
[58] "t" "i" "s" "t" "i" "c" "s"

[1] 9

In [8]:
store1 <- c(15, 9, 13, 5, 2, 17, 14)
store2 <- c(16, 7, 5, 16, 8, 13, 14)
mean(store1 + store2)
mean(store1 + store2, trim = 0.20)

[1] 22

[1] 22.6

In [2]:
m2 <- function(x){
    y <- numeric(length(x))
    for (i in 1:length(x)){
        y[i] <- (x[i]-mean(x))^2
    }
    return(mean(y))
}
v <- seq(1, 10)
m2(v)

#install.packages('e1071')
library(e1071)
# Verify with moment function in e1071 package
moment(v, order=2, center=TRUE)

[1] 8.25

[1] 8.25